m = input('Digite um valor e te darei informações sobre ele:')
print(type(m))
print('É um número?', m.isnumeric())
print('É uma letra?', m.isalpha())
print('Este é um espaço:', m.isspace())
print('Este é uma letra e/ou um número:', m.isalnum())
print('Este é um espaço em branco:', m.isspace())
print('Este é um número decimal:', m.isdecimal())
print('Este esta em maiúsculo:', m.isupper())
print('Este estas em minúsculo:', m.islower())
print('Esta capitalizada (maiúscula e minúscula):', m.istitle())
